[package]
name = "wm-tauri"
version = "0.1.0"
edition = "2021"

[lib]
name = "wm_tauri_lib"
crate-type = ["staticlib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
wm-core = { path = "../../wm-core" }
petgraph = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tauri-plugin-pilot = { git = "https://github.com/mpiton/tauri-pilot" }
fjadra = "0.2.1"
