pub mod config;
pub mod engine;
pub mod error;
pub mod graph;
pub mod install;
pub mod mcp;
pub use mcp::transport::ToolRegistry;
pub mod page;
pub mod page_repo;
pub mod parser;
pub mod reference_constant;
pub mod reference_service;
pub use reference_service as reference;
pub mod search;
pub mod shim_templates;
pub mod shared;
pub mod skill;
pub mod status;
pub mod task_board_service;
pub use task_board_service as task;
pub mod template_engine;
pub mod source_service;
pub use source_service as source;
pub mod util;
pub mod vector_db;
pub mod version;
pub use wm_embed as embed;

#[cfg(feature = "code-intel")]
pub use wm_code_intel as code_intel;
