use std::collections::BTreeMap;
use std::path::Path;

use petgraph::stable_graph::StableGraph;

use crate::engine::{GraphEdge, WikiPageMeta};

pub fn auto_generate_index(
    wiki_dir: &Path,
    graph: &StableGraph<WikiPageMeta, GraphEdge>,
) -> Result<(), String> {
    let mut content = String::new();
    content.push_str("---\n");
    content.push_str("title: Wiki Index\n");
    content.push_str("type: reference\n");
    content.push_str("---\n\n");
    content.push_str("# Wiki Index\n\n");
    content.push_str(
        "> **Do not edit this file manually.** It is auto-generated by `wm index rebuild`.\n\n",
    );

    let mut by_type: BTreeMap<String, Vec<&WikiPageMeta>> = BTreeMap::new();
    for idx in graph.node_indices() {
        let meta = &graph[idx];
        let type_name = meta.page_type.as_str();
        by_type.entry(type_name.to_string()).or_default().push(meta);
    }

    for (type_name, pages) in &by_type {
        content.push_str(&format!("## {}s\n\n", type_name));
        for meta in pages {
            let status = meta.status.as_str();
            let link = format!("{}.md", meta.id.replace(':', "/"));
            content.push_str(&format!("- [{}]({}) — *{}*\n", meta.title, link, status));
        }
        content.push('\n');
    }

    content.push_str("## Graph Stats\n\n");
    content.push_str(&format!("- **Nodes:** {}\n", graph.node_count()));
    content.push_str(&format!("- **Edges:** {}\n", graph.edge_count()));
    content.push('\n');

    let index_path = wiki_dir.join("index.md");
    std::fs::write(&index_path, &content).map_err(|e| format!("write index.md: {}", e))?;
    Ok(())
}
